### ISSUE TITLE
Taxonomy

### ISSUE THREAD

**Issue by alephreish** [mgtools/HAPiID#2]
Hi! In the preprint you mention that the reference genomes and MAGs were classified with GTDBtk, are these assignments available for download?

**Comment by mstambou** [comment]
Hi @alephreish thank you for your interest. We have annotated these MAGs in another project whose preprint is under review, you can find these taxonomic annotations at the github repo for our other paper: https://github.com/mgtools/guttree/blob/master/supplementary_files/allBin2taxon_dic.json

the json file has annotation from phylum down to species level (whenever possible) or the most specific taxonomic assignment that we could assign non-ambiguously. Hope this helps and let us know of you have any questions.

**Comment by alephreish** [comment]
@mstambou Perfect, thanks a lot!

**Comment by mstambou** [comment]
certainly. Glad we could be of help!
